[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn _core.wsgi:application"

[[services]]
name = "3k_v.2.1.10"
type = "web"
minInstances = 1

[variables]
PORT = "8000"
